/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.theoffice.duckish.ui;

/**
 *
 * @author al
 */
public class AddDrink extends javax.swing.JFrame {

    /**
     * Creates new form AddDrink
     */
    public AddDrink() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddInfoDrink = new javax.swing.JPanel();
        TitleAddInfoDrink = new javax.swing.JLabel();
        NameDrink = new javax.swing.JLabel();
        PriceDrink = new javax.swing.JLabel();
        TypeDrink = new javax.swing.JLabel();
        ClaveDrink = new javax.swing.JLabel();
        QuantityDrink = new javax.swing.JLabel();
        InNameDrinktxt = new javax.swing.JTextField();
        InPriceDrinktxt = new javax.swing.JTextField();
        InTypeDrinktxt = new javax.swing.JTextField();
        InClaveDrinktxt = new javax.swing.JTextField();
        InQuantityDrinktxt = new javax.swing.JTextField();
        btnBckAddDrink = new javax.swing.JButton();
        btnAddDrinkConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddDrink");
        setName("AddDrink"); // NOI18N
        setResizable(false);

        jPanelAddInfoDrink.setBackground(new java.awt.Color(180, 212, 222));
        jPanelAddInfoDrink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TitleAddInfoDrink.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TitleAddInfoDrink.setForeground(new java.awt.Color(0, 0, 0));
        TitleAddInfoDrink.setText("Add drink's info");

        NameDrink.setForeground(new java.awt.Color(0, 0, 0));
        NameDrink.setText("Name: ");

        PriceDrink.setForeground(new java.awt.Color(0, 0, 0));
        PriceDrink.setText("Price: ");

        TypeDrink.setForeground(new java.awt.Color(0, 0, 0));
        TypeDrink.setText("Type: ");

        ClaveDrink.setForeground(new java.awt.Color(0, 0, 0));
        ClaveDrink.setText("Clave: ");

        QuantityDrink.setForeground(new java.awt.Color(0, 0, 0));
        QuantityDrink.setText("Quantity: ");

        InTypeDrinktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InTypeDrinktxtActionPerformed(evt);
            }
        });

        InClaveDrinktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InClaveDrinktxtActionPerformed(evt);
            }
        });

        btnBckAddDrink.setIcon(new javax.swing.ImageIcon("/home/al/Escritorio/GitHub/Proyecto_ESoftware/src/main/java/org/theoffice/duckish/ui/images/back_2.png")); // NOI18N
        btnBckAddDrink.setPreferredSize(new java.awt.Dimension(50, 44));
        btnBckAddDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBckAddDrinkActionPerformed(evt);
            }
        });

        btnAddDrinkConfirm.setIcon(new javax.swing.ImageIcon("/home/al/Escritorio/GitHub/Proyecto_ESoftware/src/main/java/org/theoffice/duckish/ui/images/add.png")); // NOI18N
        btnAddDrinkConfirm.setPreferredSize(new java.awt.Dimension(50, 45));
        btnAddDrinkConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrinkConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddInfoDrinkLayout = new javax.swing.GroupLayout(jPanelAddInfoDrink);
        jPanelAddInfoDrink.setLayout(jPanelAddInfoDrinkLayout);
        jPanelAddInfoDrinkLayout.setHorizontalGroup(
            jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddInfoDrinkLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(TitleAddInfoDrink)
                .addGap(69, 69, 69))
            .addGroup(jPanelAddInfoDrinkLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBckAddDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ClaveDrink)
                            .addComponent(QuantityDrink))
                        .addComponent(TypeDrink, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PriceDrink, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NameDrink, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(InNameDrinktxt)
                        .addComponent(InPriceDrinktxt)
                        .addComponent(InTypeDrinktxt)
                        .addComponent(InClaveDrinktxt)
                        .addComponent(InQuantityDrinktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(btnAddDrinkConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddInfoDrinkLayout.setVerticalGroup(
            jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddInfoDrinkLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TitleAddInfoDrink)
                .addGap(50, 50, 50)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameDrink)
                    .addComponent(InNameDrinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceDrink)
                    .addComponent(InPriceDrinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeDrink)
                    .addComponent(InTypeDrinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaveDrink)
                    .addComponent(InClaveDrinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityDrink)
                    .addComponent(InQuantityDrinktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanelAddInfoDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddDrinkConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBckAddDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddInfoDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddInfoDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InClaveDrinktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InClaveDrinktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InClaveDrinktxtActionPerformed

    private void InTypeDrinktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InTypeDrinktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InTypeDrinktxtActionPerformed

    private void btnBckAddDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBckAddDrinkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SystemUI bck = new SystemUI();
        bck.setVisible(true);        
    }//GEN-LAST:event_btnBckAddDrinkActionPerformed

    private void btnAddDrinkConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrinkConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDrinkConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDrink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClaveDrink;
    private javax.swing.JTextField InClaveDrinktxt;
    private javax.swing.JTextField InNameDrinktxt;
    private javax.swing.JTextField InPriceDrinktxt;
    private javax.swing.JTextField InQuantityDrinktxt;
    private javax.swing.JTextField InTypeDrinktxt;
    private javax.swing.JLabel NameDrink;
    private javax.swing.JLabel PriceDrink;
    private javax.swing.JLabel QuantityDrink;
    private javax.swing.JLabel TitleAddInfoDrink;
    private javax.swing.JLabel TypeDrink;
    private javax.swing.JButton btnAddDrinkConfirm;
    private javax.swing.JButton btnBckAddDrink;
    private javax.swing.JPanel jPanelAddInfoDrink;
    // End of variables declaration//GEN-END:variables
}
