package org.theoffice.duckish.ui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.theoffice.duckish.proc.CRUD;
import org.theoffice.duckish.obj.Dish;

public class AddDesserts extends javax.swing.JFrame {

    /**
     * Creates new form AddDesserts
     */
    CRUD myCRUD = new CRUD("ichi", "gc");

    public AddDesserts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDessertPanel = new javax.swing.JPanel();
        TitleAddDessert = new javax.swing.JLabel();
        NameDessert = new javax.swing.JLabel();
        PriceDessert = new javax.swing.JLabel();
        btnBackAddDessert = new javax.swing.JButton();
        bntAddDessertConfirm = new javax.swing.JButton();
        DessertNametxt = new javax.swing.JTextField();
        DessertPricetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 400));
        setResizable(false);

        AddDessertPanel.setBackground(new java.awt.Color(22, 117, 145));
        AddDessertPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddDessertPanel.setPreferredSize(new java.awt.Dimension(380, 400));

        TitleAddDessert.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TitleAddDessert.setText("Add dessert's info");

        NameDessert.setText("Name: ");

        PriceDessert.setText("Price: ");

        btnBackAddDessert.setBackground(new java.awt.Color(22, 117, 145));
        btnBackAddDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_2.png"))); // NOI18N
        btnBackAddDessert.setPreferredSize(new java.awt.Dimension(50, 45));
        btnBackAddDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddDessertActionPerformed(evt);
            }
        });

        bntAddDessertConfirm.setBackground(new java.awt.Color(22, 117, 145));
        bntAddDessertConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        bntAddDessertConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddDessertConfirmActionPerformed(evt);
            }
        });

        DessertPricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertPricetxtActionPerformed(evt);
            }
        });
        DessertPricetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DessertPricetxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout AddDessertPanelLayout = new javax.swing.GroupLayout(AddDessertPanel);
        AddDessertPanel.setLayout(AddDessertPanelLayout);
        AddDessertPanelLayout.setHorizontalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDessertPanelLayout.createSequentialGroup()
                .addGap(49, 71, Short.MAX_VALUE)
                .addComponent(TitleAddDessert)
                .addGap(66, 66, 66))
            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddDessertPanelLayout.createSequentialGroup()
                        .addComponent(btnBackAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(bntAddDessertConfirm))
                    .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddDessertPanelLayout.createSequentialGroup()
                            .addComponent(NameDessert)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DessertNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AddDessertPanelLayout.createSequentialGroup()
                            .addComponent(PriceDessert)
                            .addGap(18, 18, 18)
                            .addComponent(DessertPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        AddDessertPanelLayout.setVerticalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleAddDessert)
                .addGap(50, 50, 50)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameDessert)
                    .addComponent(DessertNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceDessert)
                    .addComponent(DessertPricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntAddDessertConfirm)
                    .addComponent(btnBackAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DessertPricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertPricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DessertPricetxtActionPerformed

    private void bntAddDessertConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddDessertConfirmActionPerformed
        Dish myDish = new Dish();
        if (DessertNametxt.getText().trim().equals("")
                && (DessertPricetxt.getText().trim().equals(""))) {

        }
        if (myCRUD.connect()) {
            myDish.setName(DessertNametxt.getText());
            myDish.setPrice(Float.parseFloat(DessertPricetxt.getText()));
            myDish.setDescription("Dessert");
            myCRUD.connect();
            myCRUD.useDataBase();
            if (myCRUD.addDish(myDish)) {
                JOptionPane.showMessageDialog(null, "The dish has been added");
                DessertNametxt.setText("");
                DessertPricetxt.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error adding a dish");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error connecting with the Data Base");
        }
        myCRUD.disconnect();

    }//GEN-LAST:event_bntAddDessertConfirmActionPerformed

    private void btnBackAddDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddDessertActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminUI bck = new AdminUI();
        bck.setVisible(true);
    }//GEN-LAST:event_btnBackAddDessertActionPerformed

    private void DessertPricetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DessertPricetxtKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9'))
                && (c != '\b')
                && (c != KeyEvent.VK_BACK_SPACE)
                && (c != '.' || DessertPricetxt.getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_DessertPricetxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDesserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDessertPanel;
    private javax.swing.JTextField DessertNametxt;
    private javax.swing.JTextField DessertPricetxt;
    private javax.swing.JLabel NameDessert;
    private javax.swing.JLabel PriceDessert;
    private javax.swing.JLabel TitleAddDessert;
    private javax.swing.JButton bntAddDessertConfirm;
    private javax.swing.JButton btnBackAddDessert;
    // End of variables declaration//GEN-END:variables
}
