/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.theoffice.duckish.ui;



/**
 *
 * @author al
 */
public class AddDesserts extends javax.swing.JFrame {

    /**
     * Creates new form AddDesserts
     */
    public AddDesserts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDessertPanel = new javax.swing.JPanel();
        TitleAddDessert = new javax.swing.JLabel();
        NameDessert = new javax.swing.JLabel();
        PriceDessert = new javax.swing.JLabel();
        btnBackAddDessert = new javax.swing.JButton();
        bntAddDessertConfirm = new javax.swing.JButton();
        InNameDesserttxt = new javax.swing.JTextField();
        InPriceDesserttxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 400));
        setResizable(false);

        AddDessertPanel.setBackground(new java.awt.Color(180, 212, 222));
        AddDessertPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddDessertPanel.setPreferredSize(new java.awt.Dimension(380, 400));

        TitleAddDessert.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TitleAddDessert.setText("Add dessert's info");

        NameDessert.setText("Name: ");

        PriceDessert.setText("Price: ");

        btnBackAddDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_2.png"))); // NOI18N
        btnBackAddDessert.setPreferredSize(new java.awt.Dimension(50, 45));
        btnBackAddDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddDessertActionPerformed(evt);
            }
        });

        bntAddDessertConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        bntAddDessertConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddDessertConfirmActionPerformed(evt);
            }
        });

        InPriceDesserttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPriceDesserttxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddDessertPanelLayout = new javax.swing.GroupLayout(AddDessertPanel);
        AddDessertPanel.setLayout(AddDessertPanelLayout);
        AddDessertPanelLayout.setHorizontalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDessertPanelLayout.createSequentialGroup()
                .addGap(49, 103, Short.MAX_VALUE)
                .addComponent(TitleAddDessert)
                .addGap(66, 66, 66))
            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddDessertPanelLayout.createSequentialGroup()
                        .addComponent(btnBackAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(bntAddDessertConfirm))
                    .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddDessertPanelLayout.createSequentialGroup()
                            .addComponent(NameDessert)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(InNameDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AddDessertPanelLayout.createSequentialGroup()
                            .addComponent(PriceDessert)
                            .addGap(18, 18, 18)
                            .addComponent(InPriceDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        AddDessertPanelLayout.setVerticalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleAddDessert)
                .addGap(50, 50, 50)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameDessert)
                    .addComponent(InNameDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceDessert)
                    .addComponent(InPriceDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntAddDessertConfirm)
                    .addComponent(btnBackAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InPriceDesserttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPriceDesserttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPriceDesserttxtActionPerformed

    private void bntAddDessertConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddDessertConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddDessertConfirmActionPerformed

    private void btnBackAddDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddDessertActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SystemUI bck = new SystemUI();
        bck.setVisible(true);
    }//GEN-LAST:event_btnBackAddDessertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDesserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDessertPanel;
    private javax.swing.JTextField InNameDesserttxt;
    private javax.swing.JTextField InPriceDesserttxt;
    private javax.swing.JLabel NameDessert;
    private javax.swing.JLabel PriceDessert;
    private javax.swing.JLabel TitleAddDessert;
    private javax.swing.JButton bntAddDessertConfirm;
    private javax.swing.JButton btnBackAddDessert;
    // End of variables declaration//GEN-END:variables
}
