/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.theoffice.duckish.ui;

/**
 *
 * @author al
 */
public class AddDesserts extends javax.swing.JFrame {

    /**
     * Creates new form AddDesserts
     */
    public AddDesserts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDessertPanel = new javax.swing.JPanel();
        TitleAddDessert = new javax.swing.JLabel();
        NameDessert = new javax.swing.JLabel();
        PriceDessert = new javax.swing.JLabel();
        TypeDessert = new javax.swing.JLabel();
        ClaveDessert = new javax.swing.JLabel();
        QuantityDessert = new javax.swing.JLabel();
        btnBackAddDessert = new javax.swing.JButton();
        bntAddDessertConfirm = new javax.swing.JButton();
        InNameDesserttxt = new javax.swing.JTextField();
        InPriceDesserttxt = new javax.swing.JTextField();
        InTypédesserttxt = new javax.swing.JTextField();
        InClaveDesserttxt = new javax.swing.JTextField();
        InQuantityDesserttxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 600));
        setResizable(false);

        AddDessertPanel.setBackground(new java.awt.Color(180, 212, 222));
        AddDessertPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddDessertPanel.setPreferredSize(new java.awt.Dimension(380, 600));

        TitleAddDessert.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TitleAddDessert.setForeground(new java.awt.Color(0, 0, 0));
        TitleAddDessert.setText("Add dessert's info");

        NameDessert.setForeground(new java.awt.Color(0, 0, 0));
        NameDessert.setText("Name: ");

        PriceDessert.setForeground(new java.awt.Color(0, 0, 0));
        PriceDessert.setText("Price: ");

        TypeDessert.setForeground(new java.awt.Color(0, 0, 0));
        TypeDessert.setText("Type: ");

        ClaveDessert.setForeground(new java.awt.Color(0, 0, 0));
        ClaveDessert.setText("Clave: ");

        QuantityDessert.setForeground(new java.awt.Color(0, 0, 0));
        QuantityDessert.setText("Quantity: ");

        btnBackAddDessert.setIcon(new javax.swing.ImageIcon("/home/al/Escritorio/GitHub/Proyecto_ESoftware/src/main/java/org/theoffice/duckish/ui/images/back_2.png")); // NOI18N
        btnBackAddDessert.setPreferredSize(new java.awt.Dimension(50, 45));
        btnBackAddDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAddDessertActionPerformed(evt);
            }
        });

        bntAddDessertConfirm.setIcon(new javax.swing.ImageIcon("/home/al/Escritorio/GitHub/Proyecto_ESoftware/src/main/java/org/theoffice/duckish/ui/images/add.png")); // NOI18N
        bntAddDessertConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAddDessertConfirmActionPerformed(evt);
            }
        });

        InPriceDesserttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPriceDesserttxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddDessertPanelLayout = new javax.swing.GroupLayout(AddDessertPanel);
        AddDessertPanel.setLayout(AddDessertPanelLayout);
        AddDessertPanelLayout.setHorizontalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDessertPanelLayout.createSequentialGroup()
                .addGap(49, 71, Short.MAX_VALUE)
                .addComponent(TitleAddDessert)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddDessertPanelLayout.createSequentialGroup()
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddDessertPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnBackAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntAddDessertConfirm))
                    .addGroup(AddDessertPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                                .addComponent(ClaveDessert)
                                .addGap(18, 18, 18)
                                .addComponent(InClaveDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                                .addComponent(TypeDessert)
                                .addGap(18, 18, 18)
                                .addComponent(InTypédesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                                .addComponent(QuantityDessert)
                                .addGap(18, 18, 18)
                                .addComponent(InQuantityDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddDessertPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                                .addComponent(NameDessert)
                                .addGap(18, 18, 18)
                                .addComponent(InNameDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                                .addComponent(PriceDessert)
                                .addGap(18, 18, 18)
                                .addComponent(InPriceDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        AddDessertPanelLayout.setVerticalGroup(
            AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDessertPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleAddDessert)
                .addGap(50, 50, 50)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameDessert)
                    .addComponent(InNameDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceDessert)
                    .addComponent(InPriceDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeDessert)
                    .addComponent(InTypédesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaveDessert)
                    .addComponent(InClaveDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityDessert)
                    .addComponent(InQuantityDesserttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(AddDessertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackAddDessert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAddDessertConfirm, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(AddDessertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InPriceDesserttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPriceDesserttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPriceDesserttxtActionPerformed

    private void bntAddDessertConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddDessertConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAddDessertConfirmActionPerformed

    private void btnBackAddDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAddDessertActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SystemUI bck = new SystemUI();
        bck.setVisible(true);
    }//GEN-LAST:event_btnBackAddDessertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDesserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDesserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDessertPanel;
    private javax.swing.JLabel ClaveDessert;
    private javax.swing.JTextField InClaveDesserttxt;
    private javax.swing.JTextField InNameDesserttxt;
    private javax.swing.JTextField InPriceDesserttxt;
    private javax.swing.JTextField InQuantityDesserttxt;
    private javax.swing.JTextField InTypédesserttxt;
    private javax.swing.JLabel NameDessert;
    private javax.swing.JLabel PriceDessert;
    private javax.swing.JLabel QuantityDessert;
    private javax.swing.JLabel TitleAddDessert;
    private javax.swing.JLabel TypeDessert;
    private javax.swing.JButton bntAddDessertConfirm;
    private javax.swing.JButton btnBackAddDessert;
    // End of variables declaration//GEN-END:variables
}
