/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.theoffice.duckish.ui;

/**
 *
 * @author al
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminIU
     */
    public AdminUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminTitle = new javax.swing.JPanel();
        btnBackSystemUI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ContenAdminOps = new javax.swing.JPanel();
        jPanelAddDishes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddDish = new javax.swing.JButton();
        jPanelAddDrinks = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAddDrink = new javax.swing.JButton();
        jPanelAddEmployee = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAdminDeleteEmployee = new javax.swing.JButton();
        jPanelAddDesserts = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAddDessert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin opcions");
        setResizable(false);

        AdminTitle.setBackground(new java.awt.Color(13, 70, 87));

        btnBackSystemUI.setBackground(new java.awt.Color(13, 70, 87));
        btnBackSystemUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_2.png"))); // NOI18N
        btnBackSystemUI.setPreferredSize(new java.awt.Dimension(50, 45));
        btnBackSystemUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSystemUIActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(163, 100, 38));
        jLabel5.setText("Admin Options");

        javax.swing.GroupLayout AdminTitleLayout = new javax.swing.GroupLayout(AdminTitle);
        AdminTitle.setLayout(AdminTitleLayout);
        AdminTitleLayout.setHorizontalGroup(
            AdminTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackSystemUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminTitleLayout.setVerticalGroup(
            AdminTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackSystemUI, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        ContenAdminOps.setBackground(new java.awt.Color(180, 212, 222));

        jPanelAddDishes.setBackground(new java.awt.Color(38, 60, 66));
        jPanelAddDishes.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(163, 100, 38));
        jLabel1.setText("Add Dishes");

        btnAddDish.setBackground(new java.awt.Color(38, 60, 66));
        btnAddDish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddDish.setMaximumSize(new java.awt.Dimension(50, 45));
        btnAddDish.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAddDish.setPreferredSize(new java.awt.Dimension(50, 45));
        btnAddDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddDishesLayout = new javax.swing.GroupLayout(jPanelAddDishes);
        jPanelAddDishes.setLayout(jPanelAddDishesLayout);
        jPanelAddDishesLayout.setHorizontalGroup(
            jPanelAddDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDishesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
            .addGroup(jPanelAddDishesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddDishesLayout.setVerticalGroup(
            jPanelAddDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDishesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelAddDrinks.setBackground(new java.awt.Color(22, 117, 145));
        jPanelAddDrinks.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 50, 13));
        jLabel2.setText("Add Drinks");

        btnAddDrink.setBackground(new java.awt.Color(22, 117, 145));
        btnAddDrink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddDrink.setPreferredSize(new java.awt.Dimension(50, 45));
        btnAddDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddDrinksLayout = new javax.swing.GroupLayout(jPanelAddDrinks);
        jPanelAddDrinks.setLayout(jPanelAddDrinksLayout);
        jPanelAddDrinksLayout.setHorizontalGroup(
            jPanelAddDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddDrinksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
            .addGroup(jPanelAddDrinksLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnAddDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAddDrinksLayout.setVerticalGroup(
            jPanelAddDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDrinksLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAddEmployee.setBackground(new java.awt.Color(13, 70, 87));
        jPanelAddEmployee.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(163, 100, 38));
        jLabel4.setText("Delete Employee");

        btnAdminDeleteEmployee.setBackground(new java.awt.Color(38, 60, 66));
        btnAdminDeleteEmployee.setText("DELETE");
        btnAdminDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminDeleteEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddEmployeeLayout = new javax.swing.GroupLayout(jPanelAddEmployee);
        jPanelAddEmployee.setLayout(jPanelAddEmployeeLayout);
        jPanelAddEmployeeLayout.setHorizontalGroup(
            jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddEmployeeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminDeleteEmployee)
                .addGap(32, 32, 32))
        );
        jPanelAddEmployeeLayout.setVerticalGroup(
            jPanelAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddEmployeeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(btnAdminDeleteEmployee)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelAddDesserts.setBackground(new java.awt.Color(22, 117, 145));
        jPanelAddDesserts.setPreferredSize(new java.awt.Dimension(140, 140));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 50, 13));
        jLabel3.setText("Add Desserts");

        btnAddDessert.setBackground(new java.awt.Color(22, 117, 145));
        btnAddDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddDessert.setPreferredSize(new java.awt.Dimension(50, 45));
        btnAddDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDessertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddDessertsLayout = new javax.swing.GroupLayout(jPanelAddDesserts);
        jPanelAddDesserts.setLayout(jPanelAddDessertsLayout);
        jPanelAddDessertsLayout.setHorizontalGroup(
            jPanelAddDessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDessertsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAddDessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddDessertsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddDessertsLayout.createSequentialGroup()
                        .addComponent(btnAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanelAddDessertsLayout.setVerticalGroup(
            jPanelAddDessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDessertsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContenAdminOpsLayout = new javax.swing.GroupLayout(ContenAdminOps);
        ContenAdminOps.setLayout(ContenAdminOpsLayout);
        ContenAdminOpsLayout.setHorizontalGroup(
            ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenAdminOpsLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAddDesserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddDishes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
        ContenAdminOpsLayout.setVerticalGroup(
            ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenAdminOpsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAddDishes, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jPanelAddDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(ContenAdminOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAddDesserts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContenAdminOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContenAdminOps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDishActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddDish add = new AddDish();
        add.setVisible(true);
    }//GEN-LAST:event_btnAddDishActionPerformed

    private void btnAddDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrinkActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddDrink add = new AddDrink();
        add.setVisible(true);
    }//GEN-LAST:event_btnAddDrinkActionPerformed

    private void btnAdminDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDeleteEmployeeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DeleteEmployeeUI delGo = new DeleteEmployeeUI();
        delGo.setVisible(true);

    }//GEN-LAST:event_btnAdminDeleteEmployeeActionPerformed

    private void btnAddDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDessertActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddDesserts addD = new AddDesserts();
        addD.setVisible(true);
    }//GEN-LAST:event_btnAddDessertActionPerformed

    private void btnBackSystemUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSystemUIActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        this.dispose();
        SystemUI bck = new SystemUI();
        bck.setVisible(true);      
    }//GEN-LAST:event_btnBackSystemUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminTitle;
    private javax.swing.JPanel ContenAdminOps;
    private javax.swing.JButton btnAddDessert;
    private javax.swing.JButton btnAddDish;
    private javax.swing.JButton btnAddDrink;
    private javax.swing.JButton btnAdminDeleteEmployee;
    private javax.swing.JButton btnBackSystemUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAddDesserts;
    private javax.swing.JPanel jPanelAddDishes;
    private javax.swing.JPanel jPanelAddDrinks;
    private javax.swing.JPanel jPanelAddEmployee;
    // End of variables declaration//GEN-END:variables
}
