/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.theoffice.duckish.ui;

/**
 *
 * @author al
 */
public class DeleteEmployeeUI extends javax.swing.JFrame {

    /**
     * Creates new form DeleteEmployee
     */
    public DeleteEmployeeUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDeleteEmploye = new javax.swing.JPanel();
        TitleDeleteEmployee = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmployLastName = new javax.swing.JLabel();
        bckDeleteEmploye = new javax.swing.JButton();
        deleteEmployeConfirm = new javax.swing.JButton();
        InNameEmployeDeletetxt = new javax.swing.JTextField();
        InLastNameDeleteEmployeetxt = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InUserNameDeleteEmployetxt = new javax.swing.JTextField();
        InJobDeleteEmployetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Employe");
        setName("FrameDeleteEmplyee"); // NOI18N

        jPanelDeleteEmploye.setBackground(new java.awt.Color(22, 117, 145));
        jPanelDeleteEmploye.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelDeleteEmploye.setToolTipText("");
        jPanelDeleteEmploye.setAutoscrolls(true);
        jPanelDeleteEmploye.setMaximumSize(new java.awt.Dimension(380, 400));

        TitleDeleteEmployee.setBackground(new java.awt.Color(0, 0, 0));
        TitleDeleteEmployee.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        TitleDeleteEmployee.setForeground(new java.awt.Color(87, 50, 13));
        TitleDeleteEmployee.setText("Delete Employe");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 50, 13));
        jLabel2.setText("Name: ");

        EmployLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EmployLastName.setForeground(new java.awt.Color(87, 50, 13));
        EmployLastName.setText("Last name");

        bckDeleteEmploye.setBackground(new java.awt.Color(22, 117, 145));
        bckDeleteEmploye.setForeground(new java.awt.Color(22, 117, 145));
        bckDeleteEmploye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_2.png"))); // NOI18N
        bckDeleteEmploye.setMaximumSize(new java.awt.Dimension(50, 45));
        bckDeleteEmploye.setMinimumSize(new java.awt.Dimension(30, 30));
        bckDeleteEmploye.setPreferredSize(new java.awt.Dimension(50, 45));
        bckDeleteEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckDeleteEmployeActionPerformed(evt);
            }
        });

        deleteEmployeConfirm.setBackground(new java.awt.Color(204, 51, 0));
        deleteEmployeConfirm.setText("DELETE");
        deleteEmployeConfirm.setAutoscrolls(true);

        InNameEmployeDeletetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNameEmployeDeletetxtActionPerformed(evt);
            }
        });

        LastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(87, 50, 13));
        LastName.setText("UserName");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 50, 13));
        jLabel4.setText("Job");
        jLabel4.setToolTipText("");

        InJobDeleteEmployetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InJobDeleteEmployetxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteEmployeLayout = new javax.swing.GroupLayout(jPanelDeleteEmploye);
        jPanelDeleteEmploye.setLayout(jPanelDeleteEmployeLayout);
        jPanelDeleteEmployeLayout.setHorizontalGroup(
            jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(TitleDeleteEmployee)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(InNameEmployeDeletetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastName)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                                .addComponent(bckDeleteEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteEmployeConfirm))))
                    .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(EmployLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InUserNameDeleteEmployetxt)
                            .addComponent(InLastNameDeleteEmployeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InJobDeleteEmployetxt))))
                .addGap(45, 45, 45))
        );
        jPanelDeleteEmployeLayout.setVerticalGroup(
            jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteEmployeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TitleDeleteEmployee)
                .addGap(39, 39, 39)
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InNameEmployeDeletetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployLastName)
                    .addComponent(InLastNameDeleteEmployeetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(InUserNameDeleteEmployetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InJobDeleteEmployetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelDeleteEmployeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bckDeleteEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEmployeConfirm))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDeleteEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDeleteEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InNameEmployeDeletetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNameEmployeDeletetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNameEmployeDeletetxtActionPerformed

    private void InJobDeleteEmployetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InJobDeleteEmployetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InJobDeleteEmployetxtActionPerformed

    private void bckDeleteEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckDeleteEmployeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminUI bcSys = new AdminUI();
        bcSys.setVisible(true);
    }//GEN-LAST:event_bckDeleteEmployeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployLastName;
    private javax.swing.JTextField InJobDeleteEmployetxt;
    private javax.swing.JTextField InLastNameDeleteEmployeetxt;
    private javax.swing.JTextField InNameEmployeDeletetxt;
    private javax.swing.JTextField InUserNameDeleteEmployetxt;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel TitleDeleteEmployee;
    private javax.swing.JButton bckDeleteEmploye;
    private javax.swing.JButton deleteEmployeConfirm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelDeleteEmploye;
    // End of variables declaration//GEN-END:variables
}
